/**
 * Demo data for the dashboard demo mode (?demo=true).
 * Static TypeScript data — compile-safe, immutable, never corrupted by migrations.
 * Used for Supademo recordings shown to roofer prospects.
 */

import type { LeadWithDetails } from "@/components/dashboard/lead-list";

// ── Helpers ────────────────────────────────────────────────────────────

function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 3600000).toISOString();
}
function daysAgo(d: number): string {
  return hoursAgo(d * 24);
}
function monthsAgo(m: number): string {
  const dt = new Date();
  dt.setMonth(dt.getMonth() - m);
  return dt.toISOString();
}

// ── Constants ──────────────────────────────────────────────────────────

export const DEMO_BUSINESS_NAME = "Summit Roofing";
export const DEMO_CONTRACTOR_ID = "demo-contractor";

// ── 13 Demo Leads ──────────────────────────────────────────────────────

export const DEMO_LEADS: LeadWithDetails[] = [
  // ── HOT LEADS (70+) ──────────────────────────────────────────────────
  {
    id: "demo-lead-001",
    contractor_id: DEMO_CONTRACTOR_ID,
    site_id: null,
    name: "Marcus Johnson",
    email: "marcus.j@email.com",
    phone: "(813) 555-0147",
    address: "2847 Bayshore Blvd, Tampa, FL 33629",
    message: null,
    source: "estimate_widget",
    status: "new",
    estimate_low: 14000,
    estimate_high: 18000,
    estimate_material: "Standing Seam Metal",
    estimate_roof_sqft: 2800,
    estimate_materials: null,
    living_estimate_id: null,
    property_data_id: "demo-pd-001",
    timeline: "1_3_months",
    financing_interest: "maybe",
    temperature: "hot",
    contacted_at: null,
    notes: null,
    estimate_pitch_degrees: 22,
    estimate_segments: 4,
    created_at: hoursAgo(3),
    heatScore: 82,
    propertyData: {
      estimated_value: 385000,
      value_range_low: 365000,
      value_range_high: 405000,
      year_built: 1997,
      estimated_roof_age_years: 27,
      is_original_roof: true,
      in_replacement_window: true,
      owner_names: "Marcus & Linda Johnson",
      owner_occupied: true,
      last_sale_date: daysAgo(365 * 4),
      last_sale_price: 310000,
      square_footage: 2450,
      flood_zone: "X",
      fema_disaster_count: 4,
      county_name: "Hillsborough",
    },
    chatPreview: {
      messages: [
        { role: "user", content: "Hi, I'm looking at metal roofing options for my house. Can you tell me about standing seam?" },
        { role: "assistant", content: "Standing seam metal is a great choice for Florida weather — it handles high winds and lasts 40-60 years. Would you like me to pull up an estimate for your home?" },
        { role: "user", content: "Yes please. I'm at 2847 Bayshore Blvd. Also, when could you start?" },
        { role: "assistant", content: "I can get you an estimate right now. For scheduling, most projects start within 2-3 weeks of signing. Let me pull up the numbers for your roof." },
      ],
      stage: "decision",
      messageCount: 4,
      topics: ["price_seeking", "scheduling", "general_info"],
    },
    signals: {
      widgetViews: 6,
      lastViewAt: hoursAgo(1),
      materialSwitches: 3,
      materialsCompared: ["Architectural Shingle", "Standing Seam Metal"],
      chatDepthTier: "high_intent",
      priceAdjustments: 2,
    },
    alerts: [{ type: "hot_activity", label: "Viewed 6x today" }],
  },
  {
    id: "demo-lead-002",
    contractor_id: DEMO_CONTRACTOR_ID,
    site_id: null,
    name: "Sarah Chen",
    email: "sarah.chen@email.com",
    phone: "(727) 555-0293",
    address: "1523 4th St N, St. Petersburg, FL 33704",
    message: null,
    source: "ai_chatbot",
    status: "contacted",
    estimate_low: 9000,
    estimate_high: 13000,
    estimate_material: "Architectural Shingle",
    estimate_roof_sqft: 2100,
    estimate_materials: null,
    living_estimate_id: null,
    property_data_id: "demo-pd-002",
    timeline: "now",
    financing_interest: "yes",
    temperature: "hot",
    contacted_at: hoursAgo(2),
    notes: "Called — she's getting 3 quotes. Inspection scheduled for Thursday.",
    estimate_pitch_degrees: 18,
    estimate_segments: 3,
    created_at: daysAgo(1),
    heatScore: 76,
    propertyData: {
      estimated_value: 290000,
      value_range_low: 275000,
      value_range_high: 305000,
      year_built: 1988,
      estimated_roof_age_years: 36,
      is_original_roof: false,
      in_replacement_window: true,
      owner_names: "Sarah Chen",
      owner_occupied: true,
      last_sale_date: daysAgo(365 * 2),
      last_sale_price: 255000,
      square_footage: 1850,
      flood_zone: "AE",
      fema_disaster_count: 5,
      county_name: "Pinellas",
    },
    chatPreview: {
      messages: [
        { role: "user", content: "I need a new roof — mine is leaking after the last storm. How much would it cost?" },
        { role: "assistant", content: "I'm sorry to hear about the leak. For a home your size, a full replacement typically runs $9,000-$13,000 for architectural shingles. Would you like an exact estimate?" },
        { role: "user", content: "Yes. I'm at 1523 4th St N, St Pete. Do you work with insurance?" },
        { role: "assistant", content: "We work with all major insurers and can help document the damage for your claim. Let me pull up the estimate for your address." },
        { role: "user", content: "Great. Can I schedule an inspection this week?" },
      ],
      stage: "decision",
      messageCount: 5,
      topics: ["price_seeking", "insurance", "scheduling"],
    },
    signals: {
      widgetViews: 4,
      lastViewAt: hoursAgo(6),
      materialSwitches: 1,
      materialsCompared: ["3-Tab Shingle", "Architectural Shingle"],
      chatDepthTier: "high_intent",
      priceAdjustments: 1,
    },
    alerts: [{ type: "replacement", label: "Replacement window" }],
  },
  {
    id: "demo-lead-003",
    contractor_id: DEMO_CONTRACTOR_ID,
    site_id: null,
    name: "David Rodriguez",
    email: "david.r@email.com",
    phone: "(813) 555-0385",
    address: "904 W Swann Ave, Tampa, FL 33606",
    message: null,
    source: "estimate_widget",
    status: "appointment_set",
    estimate_low: 16000,
    estimate_high: 22000,
    estimate_material: "Standing Seam Metal",
    estimate_roof_sqft: 3200,
    estimate_materials: null,
    living_estimate_id: null,
    property_data_id: "demo-pd-003",
    timeline: "1_3_months",
    financing_interest: "yes",
    temperature: "hot",
    contacted_at: daysAgo(1),
    notes: "New homeowner, very interested in metal. Inspection Monday 10am.",
    estimate_pitch_degrees: 25,
    estimate_segments: 6,
    created_at: daysAgo(2),
    heatScore: 71,
    propertyData: {
      estimated_value: 445000,
      value_range_low: 420000,
      value_range_high: 470000,
      year_built: 2001,
      estimated_roof_age_years: 23,
      is_original_roof: true,
      in_replacement_window: true,
      owner_names: "David & Elena Rodriguez",
      owner_occupied: true,
      last_sale_date: monthsAgo(3),
      last_sale_price: 425000,
      square_footage: 2800,
      flood_zone: "X",
      fema_disaster_count: 3,
      county_name: "Hillsborough",
    },
    chatPreview: {
      messages: [
        { role: "user", content: "We just bought this house and the roof looks like it needs replacing. What are our options?" },
        { role: "assistant", content: "Congratulations on the new home! With a roof that's about 23 years old, you're right in the replacement window. I'd recommend looking at standing seam metal — it's ideal for Florida and lasts 40-60 years." },
        { role: "user", content: "What about financing? This is a big expense right after buying the house." },
      ],
      stage: "consideration",
      messageCount: 3,
      topics: ["general_info", "price_seeking"],
    },
    signals: {
      widgetViews: 3,
      lastViewAt: daysAgo(1),
      materialSwitches: 2,
      materialsCompared: ["Architectural Shingle", "Standing Seam Metal", "Tile"],
      chatDepthTier: "engaged",
      priceAdjustments: 1,
    },
    alerts: [
      { type: "new_homeowner", label: "New homeowner" },
      { type: "replacement", label: "Replacement window" },
    ],
  },

  // ── WARM LEADS (40-69) ───────────────────────────────────────────────
  {
    id: "demo-lead-004",
    contractor_id: DEMO_CONTRACTOR_ID,
    site_id: null,
    name: "Lisa Thompson",
    email: "lisa.t@email.com",
    phone: "(941) 555-0412",
    address: "3102 Riverview Dr, Bradenton, FL 34205",
    message: null,
    source: "estimate_widget",
    status: "quoted",
    estimate_low: 22000,
    estimate_high: 28000,
    estimate_material: "Concrete Tile",
    estimate_roof_sqft: 3500,
    estimate_materials: null,
    living_estimate_id: null,
    property_data_id: "demo-pd-004",
    timeline: "1_3_months",
    financing_interest: "yes",
    temperature: "warm",
    contacted_at: daysAgo(3),
    notes: "Sent quote on Friday. Following up Wednesday.",
    estimate_pitch_degrees: 30,
    estimate_segments: 5,
    created_at: daysAgo(5),
    heatScore: 58,
    propertyData: {
      estimated_value: 420000,
      value_range_low: 395000,
      value_range_high: 445000,
      year_built: 1992,
      estimated_roof_age_years: 32,
      is_original_roof: false,
      in_replacement_window: true,
      owner_names: "Lisa & Mark Thompson",
      owner_occupied: true,
      last_sale_date: daysAgo(365 * 8),
      last_sale_price: 280000,
      square_footage: 3100,
      flood_zone: "AE",
      fema_disaster_count: 6,
      county_name: "Manatee",
    },
    chatPreview: {
      messages: [
        { role: "user", content: "I'm comparing tile vs metal for a re-roof. What do you recommend?" },
        { role: "assistant", content: "Both are excellent for Florida. Tile lasts 50+ years and handles hurricanes well. Metal is lighter and installs faster. It depends on your budget and aesthetic preference." },
      ],
      stage: "consideration",
      messageCount: 2,
      topics: ["comparison", "general_info"],
    },
    signals: {
      widgetViews: 3,
      lastViewAt: daysAgo(2),
      materialSwitches: 4,
      materialsCompared: ["Architectural Shingle", "Standing Seam Metal", "Concrete Tile"],
      chatDepthTier: "engaged",
      priceAdjustments: 3,
    },
    alerts: [],
  },
  {
    id: "demo-lead-005",
    contractor_id: DEMO_CONTRACTOR_ID,
    site_id: null,
    name: "James Wilson",
    email: "jwilson@email.com",
    phone: "(727) 555-0518",
    address: "678 Central Ave, St. Petersburg, FL 33701",
    message: null,
    source: "ai_chatbot",
    status: "new",
    estimate_low: 8000,
    estimate_high: 12000,
    estimate_material: "Architectural Shingle",
    estimate_roof_sqft: 1900,
    estimate_materials: null,
    living_estimate_id: null,
    property_data_id: "demo-pd-005",
    timeline: "no_timeline",
    financing_interest: "no",
    temperature: "warm",
    contacted_at: null,
    notes: null,
    estimate_pitch_degrees: 15,
    estimate_segments: 2,
    created_at: daysAgo(2),
    heatScore: 52,
    propertyData: {
      estimated_value: 245000,
      value_range_low: 230000,
      value_range_high: 260000,
      year_built: 2005,
      estimated_roof_age_years: 19,
      is_original_roof: true,
      in_replacement_window: true,
      owner_names: "James Wilson",
      owner_occupied: true,
      last_sale_date: daysAgo(365 * 6),
      last_sale_price: 195000,
      square_footage: 1650,
      flood_zone: "X",
      fema_disaster_count: 3,
      county_name: "Pinellas",
    },
    chatPreview: {
      messages: [
        { role: "user", content: "How long does a new roof last? My shingles are starting to curl." },
        { role: "assistant", content: "Curling shingles usually mean the roof is past its prime. Architectural shingles typically last 25-30 years. Given your roof is about 19 years old, it's worth planning ahead." },
        { role: "user", content: "Do you offer warranties? I want to make sure it lasts." },
      ],
      stage: "discovery",
      messageCount: 3,
      topics: ["general_info", "trust_seeking"],
    },
    signals: {
      widgetViews: 3,
      lastViewAt: daysAgo(1),
      materialSwitches: 0,
      chatDepthTier: "engaged",
      priceAdjustments: 0,
    },
    alerts: [],
  },
  {
    id: "demo-lead-006",
    contractor_id: DEMO_CONTRACTOR_ID,
    site_id: null,
    name: "Ashley Martinez",
    email: "ashley.m@email.com",
    phone: "(813) 555-0624",
    address: "4412 Gandy Blvd, Tampa, FL 33611",
    message: "Storm damage to roof — need assessment",
    source: "ai_chatbot",
    status: "contacted",
    estimate_low: 7000,
    estimate_high: 10000,
    estimate_material: "Architectural Shingle",
    estimate_roof_sqft: 1700,
    estimate_materials: null,
    living_estimate_id: null,
    property_data_id: "demo-pd-006",
    timeline: "now",
    financing_interest: "no",
    temperature: "warm",
    contacted_at: daysAgo(1),
    notes: "Insurance claim in progress. Adjuster visit scheduled.",
    estimate_pitch_degrees: 20,
    estimate_segments: 3,
    created_at: daysAgo(3),
    heatScore: 47,
    propertyData: {
      estimated_value: 220000,
      value_range_low: 205000,
      value_range_high: 235000,
      year_built: 2010,
      estimated_roof_age_years: 14,
      is_original_roof: true,
      in_replacement_window: false,
      owner_names: "Ashley Martinez",
      owner_occupied: true,
      last_sale_date: daysAgo(365 * 3),
      last_sale_price: 195000,
      square_footage: 1500,
      flood_zone: "AE",
      fema_disaster_count: 4,
      county_name: "Hillsborough",
    },
    chatPreview: {
      messages: [
        { role: "user", content: "We had storm damage — there are missing shingles and a leak in the bedroom. Do you work with insurance?" },
        { role: "assistant", content: "We work with all major insurers and can help document the damage for your claim. We'll do a thorough inspection and provide the documentation your adjuster needs." },
      ],
      stage: "discovery",
      messageCount: 2,
      topics: ["insurance", "emergency"],
    },
    signals: {
      widgetViews: 2,
      lastViewAt: daysAgo(2),
      materialSwitches: 0,
      chatDepthTier: "browsing",
      priceAdjustments: 0,
    },
    alerts: [],
  },
  {
    id: "demo-lead-007",
    contractor_id: DEMO_CONTRACTOR_ID,
    site_id: null,
    name: "Robert Taylor",
    email: "r.taylor@email.com",
    phone: "(727) 555-0731",
    address: "891 Clearwater Beach Rd, Clearwater, FL 33767",
    message: null,
    source: "estimate_widget",
    status: "new",
    estimate_low: 15000,
    estimate_high: 20000,
    estimate_material: "Standing Seam Metal",
    estimate_roof_sqft: 2600,
    estimate_materials: null,
    living_estimate_id: null,
    property_data_id: "demo-pd-007",
    timeline: "no_timeline",
    financing_interest: "maybe",
    temperature: "warm",
    contacted_at: null,
    notes: null,
    estimate_pitch_degrees: 20,
    estimate_segments: 4,
    created_at: daysAgo(1),
    heatScore: 43,
    propertyData: {
      estimated_value: 355000,
      value_range_low: 335000,
      value_range_high: 375000,
      year_built: 2003,
      estimated_roof_age_years: 21,
      is_original_roof: true,
      in_replacement_window: true,
      owner_names: "Robert & Joan Taylor",
      owner_occupied: true,
      last_sale_date: daysAgo(365 * 10),
      last_sale_price: 220000,
      square_footage: 2200,
      flood_zone: "VE",
      fema_disaster_count: 5,
      county_name: "Pinellas",
    },
    chatPreview: undefined,
    signals: {
      widgetViews: 2,
      lastViewAt: daysAgo(1),
      materialSwitches: 1,
      materialsCompared: ["Architectural Shingle", "Standing Seam Metal"],
      chatDepthTier: undefined,
      priceAdjustments: 0,
    },
    alerts: [],
  },

  // ── COOL LEADS (<40) ─────────────────────────────────────────────────
  {
    id: "demo-lead-008",
    contractor_id: DEMO_CONTRACTOR_ID,
    site_id: null,
    name: "Karen White",
    email: null,
    phone: "(813) 555-0842",
    address: "2201 N Dale Mabry, Tampa, FL 33607",
    message: "Need roof estimate",
    source: "contact_form",
    status: "new",
    estimate_low: 6000,
    estimate_high: 9000,
    estimate_material: null,
    estimate_roof_sqft: null,
    estimate_materials: null,
    living_estimate_id: null,
    property_data_id: null,
    timeline: null,
    financing_interest: null,
    temperature: null,
    contacted_at: null,
    notes: null,
    estimate_pitch_degrees: null,
    estimate_segments: null,
    created_at: daysAgo(3),
    heatScore: 28,
    propertyData: undefined,
    chatPreview: undefined,
    signals: {
      widgetViews: 0,
      materialSwitches: 0,
      priceAdjustments: 0,
    },
    alerts: [{ type: "stale", label: "48h+ no contact" }],
  },
  {
    id: "demo-lead-009",
    contractor_id: DEMO_CONTRACTOR_ID,
    site_id: null,
    name: "Michael Brown",
    email: "mbrown@email.com",
    phone: "(941) 555-0953",
    address: "567 Main St, Sarasota, FL 34236",
    message: null,
    source: "estimate_widget",
    status: "contacted",
    estimate_low: 8000,
    estimate_high: 11000,
    estimate_material: "Architectural Shingle",
    estimate_roof_sqft: 1800,
    estimate_materials: null,
    living_estimate_id: null,
    property_data_id: "demo-pd-009",
    timeline: "no_timeline",
    financing_interest: "no",
    temperature: "browsing",
    contacted_at: daysAgo(5),
    notes: "Left voicemail. No callback yet.",
    estimate_pitch_degrees: 15,
    estimate_segments: 2,
    created_at: daysAgo(7),
    heatScore: 19,
    propertyData: {
      estimated_value: 195000,
      value_range_low: 180000,
      value_range_high: 210000,
      year_built: 2012,
      estimated_roof_age_years: 12,
      is_original_roof: true,
      in_replacement_window: false,
      owner_names: "Michael Brown",
      owner_occupied: true,
      last_sale_date: daysAgo(365 * 5),
      last_sale_price: 165000,
      square_footage: 1400,
      flood_zone: "X",
      fema_disaster_count: 2,
      county_name: "Sarasota",
    },
    chatPreview: undefined,
    signals: {
      widgetViews: 1,
      lastViewAt: daysAgo(7),
      materialSwitches: 0,
      chatDepthTier: undefined,
      priceAdjustments: 0,
    },
    alerts: [],
  },
  {
    id: "demo-lead-010",
    contractor_id: DEMO_CONTRACTOR_ID,
    site_id: null,
    name: "Patricia Davis",
    email: "p.davis@email.com",
    phone: "(727) 555-1064",
    address: "345 Beach Dr NE, St. Petersburg, FL 33701",
    message: null,
    source: "estimate_widget",
    status: "lost",
    estimate_low: 9000,
    estimate_high: 13000,
    estimate_material: "Architectural Shingle",
    estimate_roof_sqft: 2000,
    estimate_materials: null,
    living_estimate_id: null,
    property_data_id: "demo-pd-010",
    timeline: "1_3_months",
    financing_interest: "no",
    temperature: "browsing",
    contacted_at: daysAgo(10),
    notes: "Went with another contractor — price was lower.",
    estimate_pitch_degrees: 18,
    estimate_segments: 3,
    created_at: daysAgo(14),
    heatScore: 12,
    propertyData: {
      estimated_value: 310000,
      value_range_low: 290000,
      value_range_high: 330000,
      year_built: 2008,
      estimated_roof_age_years: 16,
      is_original_roof: true,
      in_replacement_window: false,
      owner_names: "Patricia Davis",
      owner_occupied: true,
      last_sale_date: daysAgo(365 * 7),
      last_sale_price: 235000,
      square_footage: 1750,
      flood_zone: "X",
      fema_disaster_count: 3,
      county_name: "Pinellas",
    },
    chatPreview: undefined,
    signals: {
      widgetViews: 1,
      lastViewAt: daysAgo(14),
      materialSwitches: 0,
      chatDepthTier: undefined,
      priceAdjustments: 0,
    },
    alerts: [],
  },

  // ── WON / COMPLETED (for review stats) ─────────────────────────────
  {
    id: "demo-lead-011",
    contractor_id: DEMO_CONTRACTOR_ID,
    site_id: null,
    name: "Tom Henderson",
    email: "tom.h@email.com",
    phone: "(813) 555-1175",
    address: "1200 W Platt St, Tampa, FL 33606",
    message: null,
    source: "estimate_widget",
    status: "completed",
    estimate_low: 11000,
    estimate_high: 14500,
    estimate_material: "Architectural Shingle",
    estimate_roof_sqft: 2300,
    estimate_materials: null,
    living_estimate_id: null,
    property_data_id: "demo-pd-011",
    timeline: "now",
    financing_interest: "no",
    temperature: "hot",
    contacted_at: daysAgo(18),
    notes: "Job complete. Very happy with the work.",
    estimate_pitch_degrees: 22,
    estimate_segments: 4,
    created_at: daysAgo(21),
    heatScore: 5,
    propertyData: {
      estimated_value: 340000,
      year_built: 1995,
      estimated_roof_age_years: 29,
      is_original_roof: true,
      in_replacement_window: true,
      owner_names: "Tom Henderson",
      owner_occupied: true,
      square_footage: 2100,
      flood_zone: "X",
      fema_disaster_count: 4,
      county_name: "Hillsborough",
    },
    chatPreview: undefined,
    signals: { widgetViews: 2, materialSwitches: 0, priceAdjustments: 0 },
    alerts: [],
  },
  {
    id: "demo-lead-012",
    contractor_id: DEMO_CONTRACTOR_ID,
    site_id: null,
    name: "Angela Foster",
    email: "angela.f@email.com",
    phone: "(727) 555-1286",
    address: "890 Treasure Island Cswy, Treasure Island, FL 33706",
    message: null,
    source: "ai_chatbot",
    status: "completed",
    estimate_low: 18000,
    estimate_high: 24000,
    estimate_material: "Standing Seam Metal",
    estimate_roof_sqft: 2700,
    estimate_materials: null,
    living_estimate_id: null,
    property_data_id: "demo-pd-012",
    timeline: "now",
    financing_interest: "yes",
    temperature: "hot",
    contacted_at: daysAgo(10),
    notes: "Metal roof installed. She's thrilled.",
    estimate_pitch_degrees: 20,
    estimate_segments: 4,
    created_at: daysAgo(14),
    heatScore: 5,
    propertyData: {
      estimated_value: 415000,
      year_built: 1990,
      estimated_roof_age_years: 34,
      owner_names: "Angela Foster",
      owner_occupied: true,
      square_footage: 2400,
      flood_zone: "VE",
      fema_disaster_count: 6,
      county_name: "Pinellas",
    },
    chatPreview: undefined,
    signals: { widgetViews: 5, materialSwitches: 2, priceAdjustments: 1 },
    alerts: [],
  },
  {
    id: "demo-lead-013",
    contractor_id: DEMO_CONTRACTOR_ID,
    site_id: null,
    name: "Carlos Reyes",
    email: "carlos.r@email.com",
    phone: "(813) 555-1397",
    address: "3456 W Kennedy Blvd, Tampa, FL 33609",
    message: null,
    source: "estimate_widget",
    status: "won",
    estimate_low: 9500,
    estimate_high: 13000,
    estimate_material: "Architectural Shingle",
    estimate_roof_sqft: 2000,
    estimate_materials: null,
    living_estimate_id: null,
    property_data_id: "demo-pd-013",
    timeline: "1_3_months",
    financing_interest: "maybe",
    temperature: "hot",
    contacted_at: daysAgo(5),
    notes: "Signed. Starting next week.",
    estimate_pitch_degrees: 18,
    estimate_segments: 3,
    created_at: daysAgo(7),
    heatScore: 5,
    propertyData: {
      estimated_value: 275000,
      year_built: 2000,
      estimated_roof_age_years: 24,
      owner_names: "Carlos & Maria Reyes",
      owner_occupied: true,
      square_footage: 1800,
      flood_zone: "X",
      fema_disaster_count: 3,
      county_name: "Hillsborough",
    },
    chatPreview: undefined,
    signals: { widgetViews: 4, materialSwitches: 1, priceAdjustments: 0 },
    alerts: [],
  },
];

// ── Pre-Computed Stats ─────────────────────────────────────────────────

export const DEMO_STATS = {
  pipelineValue: 127000,
  hotLeads: 3,
  avgResponse: "2.4h",
  staleLeads: 2,
};

// ── Copilot Lead Console Data ──────────────────────────────────────────

export interface DemoCopilotLead {
  id: string;
  name: string;
  phone: string | null;
  email: string | null;
  address: string | null;
  status: string;
  temperature: string | null;
  source: string;
  estimate_low: number | null;
  estimate_high: number | null;
  estimate_material: string | null;
  created_at: string;
  created_ago: string;
  contacted_at: string | null;
  notes: string | null;
  copilot_status_pills: string[];
  copilot_action_log: { action: string; timestamp: string }[];
  lead_score: number | null;
}

function formatTimeAgo(dateStr: string): string {
  const diff = Date.now() - new Date(dateStr).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days === 1) return "Yesterday";
  if (days < 7) return `${days}d ago`;
  return `${Math.floor(days / 7)}w ago`;
}

export const DEMO_COPILOT_LEADS: DemoCopilotLead[] = DEMO_LEADS.map((l) => ({
  id: l.id,
  name: l.name,
  phone: l.phone,
  email: l.email,
  address: l.address,
  status: l.status,
  temperature: l.temperature,
  source: l.source,
  estimate_low: l.estimate_low,
  estimate_high: l.estimate_high,
  estimate_material: l.estimate_material,
  created_at: l.created_at,
  created_ago: formatTimeAgo(l.created_at),
  contacted_at: l.contacted_at,
  notes: l.notes,
  copilot_status_pills: l.status === "appointment_set" ? ["Inspection Set"] : l.status === "won" ? ["Called", "Inspection Set", "Quote Sent", "Won"] : [],
  copilot_action_log: l.contacted_at
    ? [{ action: "Called", timestamp: l.contacted_at }]
    : [],
  lead_score: l.heatScore,
}));

// Pre-generated AI drafts (3 tones) for top leads
export const DEMO_AI_DRAFTS: Record<string, { direct: string; warm: string; formal: string }> = {
  "demo-lead-001": {
    direct: "Hey Marcus, saw you were looking at metal roofing. I can come take measurements this week — does Tuesday or Thursday work?",
    warm: "Hi Marcus! Thanks for checking out our metal roofing options. I'd love to walk you through the differences in person. When's a good time for a free inspection?",
    formal: "Marcus, thank you for your interest in standing seam metal roofing. I would be happy to schedule a complimentary inspection at your convenience to discuss your options.",
  },
  "demo-lead-002": {
    direct: "Sarah, I know you're getting quotes — happy to walk through ours in detail. Our GAF Master Elite warranty is hard to beat. Free to chat?",
    warm: "Hi Sarah! Just following up on your estimate. I know choosing a roofer is a big decision — happy to answer any questions about our work or warranty.",
    formal: "Sarah, I wanted to follow up regarding the estimate we discussed. Please don't hesitate to reach out with any questions about our warranty coverage or installation process.",
  },
  "demo-lead-003": {
    direct: "David, confirming your inspection for Monday at 10am. I'll bring metal and shingle samples so you can compare in person.",
    warm: "Hey David! Looking forward to Monday's inspection. Congrats again on the new house — we'll make sure your roof is set for the next 40 years.",
    formal: "David, this is a confirmation for your roofing inspection scheduled for Monday at 10:00 AM. We look forward to discussing the best options for your new home.",
  },
  "demo-lead-004": {
    direct: "Lisa, just checking in on the tile quote. Happy to adjust the scope or walk through the numbers. No pressure.",
    warm: "Hi Lisa! Wanted to follow up on your estimate. I know tile is a bigger investment, but it'll outlast everything else on the market. Happy to chat through it!",
    formal: "Lisa, I wanted to follow up regarding the estimate we provided for your concrete tile installation. Please let us know if you have any questions about the scope or pricing.",
  },
  "demo-lead-005": {
    direct: "James, your shingles curling at 19 years is pretty normal. Want me to come take a look before it gets worse? Free inspection.",
    warm: "Hey James! I saw you were asking about roof lifespan. At 19 years with curling shingles, now's a great time to plan ahead. Want a free inspection?",
    formal: "James, based on our conversation about your roof's condition, I recommend scheduling a complimentary inspection to assess the curling shingles you mentioned.",
  },
};

// View counts for Copilot page
export const DEMO_VIEW_COUNTS: Record<string, number> = {
  "demo-lead-001": 6,
  "demo-lead-002": 4,
  "demo-lead-003": 3,
  "demo-lead-004": 3,
  "demo-lead-005": 3,
  "demo-lead-006": 2,
  "demo-lead-007": 2,
  "demo-lead-009": 1,
  "demo-lead-010": 1,
  "demo-lead-011": 2,
  "demo-lead-012": 5,
  "demo-lead-013": 4,
};

// Pre-recorded Copilot conversation
export const DEMO_COPILOT_CHAT = [
  {
    id: "demo-chat-1",
    role: "user" as const,
    parts: [{ type: "text" as const, text: "How am I doing this week?" }],
  },
  {
    id: "demo-chat-2",
    role: "assistant" as const,
    parts: [{ type: "text" as const, text: "Solid week — 5 new leads, 3 hot. Your pipeline value is $127K across 13 active leads.\n\nYour avg response time is 2.4 hours, which is good. One thing: you've got 2 uncontacted leads over 48 hours old (Karen White, 3 days). Want me to draft a follow-up?" }],
  },
  {
    id: "demo-chat-3",
    role: "user" as const,
    parts: [{ type: "text" as const, text: "Show me hot leads" }],
  },
  {
    id: "demo-chat-4",
    role: "assistant" as const,
    parts: [{ type: "text" as const, text: "You've got 3 hot leads right now:\n\n1. **Marcus Johnson** — $14K–$18K metal roof, viewed estimate 6x, asked about scheduling. Came in 3h ago.\n2. **Sarah Chen** — $9K–$13K shingle, high-intent chat, insurance interest. Contacted 2h ago.\n3. **David Rodriguez** — $16K–$22K metal, new homeowner, inspection set. Came in 2d ago.\n\nMarcus is freshest and highly engaged. I'd prioritize him." }],
  },
  {
    id: "demo-chat-5",
    role: "user" as const,
    parts: [{ type: "text" as const, text: "Is Johnson still interested?" }],
  },
  {
    id: "demo-chat-6",
    role: "assistant" as const,
    parts: [{ type: "text" as const, text: "Very much so. Marcus checked his estimate 6 times — last visit was 1 hour ago. He toggled between architectural shingles and standing seam metal 3 times, which usually means he's comparing options seriously.\n\nHis chat showed high intent — he asked about scheduling and provided his address. I'd call him today while he's actively engaged." }],
  },
  {
    id: "demo-chat-7",
    role: "user" as const,
    parts: [{ type: "text" as const, text: "What do we know about his roof?" }],
  },
  {
    id: "demo-chat-8",
    role: "assistant" as const,
    parts: [{ type: "text" as const, text: "Marcus's home at 2847 Bayshore Blvd was built in 1997 — that puts the roof at about 27 years old. If it's the original roof, it's well past the typical replacement window for shingles.\n\n**Property snapshot:**\n• Home value: ~$385K\n• 2,450 sqft\n• Flood zone: X (low risk)\n• 4 FEMA disaster declarations in Hillsborough County\n\nHis $14K–$18K estimate is about 4% of home value — very affordable by comparison. Strong candidate." }],
  },
  {
    id: "demo-chat-9",
    role: "user" as const,
    parts: [{ type: "text" as const, text: "Draft a follow-up text for him" }],
  },
  {
    id: "demo-chat-10",
    role: "assistant" as const,
    parts: [{ type: "text" as const, text: "Here's a draft:\n\n> \"Hey Marcus, saw you were looking at metal roofing options for your Bayshore home. Standing seam is a great fit for Florida weather — I can come take measurements this week. Does Tuesday or Thursday work better?\"\n\nShort, references his interest in metal, and offers specific times. Want me to adjust the tone?" }],
  },
];

// ── Review Stats ───────────────────────────────────────────────────────

export const DEMO_REVIEW_DATA = {
  googleReviewUrl: "https://g.page/SummitRoofingTampa",
  reviewEnabled: true,
  businessName: DEMO_BUSINESS_NAME,
  emailSubject: "How was your experience with Summit Roofing?",
  emailHeading: "Thanks for choosing Summit Roofing!",
  emailBody: "We hope everything went well. If you have a minute, a quick review would really help us out.",
  emailButton: "⭐ Leave a Review",
  emailDelay: "1_day",
  stats: {
    totalSent: 12,
    totalClicked: 8,
    totalReviewed: 5,
    clickRate: "67%",
    reviewRate: "42%",
  },
  recentRequests: [
    { leadName: "Tom Henderson", status: "reviewed", sentAt: daysAgo(14), sentAgo: "2w ago" },
    { leadName: "Angela Foster", status: "clicked", sentAt: daysAgo(5), sentAgo: "5d ago" },
    { leadName: "Linda Park", status: "sent", sentAt: daysAgo(3), sentAgo: "3d ago" },
    { leadName: "Kevin Nguyen", status: "reviewed", sentAt: daysAgo(21), sentAgo: "3w ago" },
    { leadName: "Diane Russell", status: "clicked", sentAt: daysAgo(7), sentAgo: "1w ago" },
  ],
  completedLeads: [
    { id: "demo-lead-013", name: "Carlos Reyes", email: "carlos.r@email.com", completedAgo: "3d ago", hasReviewRequest: false },
  ],
};

// ── Riley Analytics ────────────────────────────────────────────────────

export const DEMO_RILEY_ANALYTICS = {
  totalConversations: 47,
  thisWeek: 8,
  today: 2,
  leadsCaptured: 13,
  captureRate: "28%",
  avgMessages: 6.2,
  topQuestions: [
    { type: "Pricing", count: 16, pct: 34 },
    { type: "Materials", count: 10, pct: 22 },
    { type: "Timeline", count: 8, pct: 18 },
    { type: "Insurance", count: 6, pct: 12 },
    { type: "Warranty", count: 4, pct: 8 },
    { type: "Other", count: 3, pct: 6 },
  ],
  // 30 days of daily conversation counts
  dailyVolume: Array.from({ length: 30 }, (_, i) => ({
    date: daysAgo(29 - i).split("T")[0],
    count: i < 5 ? 0 : Math.floor(Math.random() * 3) + (i > 20 ? 2 : 1),
  })),
  sampleConversations: [
    {
      id: "demo-conv-1",
      leadName: "Marcus Johnson",
      messageCount: 4,
      stage: "decision",
      createdAt: hoursAgo(3),
      preview: "Hi, I'm looking at metal roofing options...",
    },
    {
      id: "demo-conv-2",
      leadName: "Sarah Chen",
      messageCount: 5,
      stage: "decision",
      createdAt: daysAgo(1),
      preview: "I need a new roof — mine is leaking...",
    },
    {
      id: "demo-conv-3",
      leadName: "Ashley Martinez",
      messageCount: 2,
      stage: "discovery",
      createdAt: daysAgo(3),
      preview: "We had storm damage — there are missing shingles...",
    },
    {
      id: "demo-conv-4",
      leadName: "James Wilson",
      messageCount: 3,
      stage: "discovery",
      createdAt: daysAgo(2),
      preview: "How long does a new roof last?...",
    },
  ],
};

// ── Chatbot Config (fully trained state) ───────────────────────────────

export const DEMO_CHATBOT_CONFIG = {
  offers_free_inspection: true,
  materials_brands: ["GAF Timberline HD", "Owens Corning Duration", "CertainTeed Landmark"],
  process_steps: "1) Free inspection with measurements, 2) Detailed written estimate, 3) Financing options presented, 4) Roof replacement or repair, 5) Final walkthrough & cleanup",
  does_insurance_work: true,
  insurance_description: "We work with all major insurers. Our team will help document damage and file claims.",
  financing_provider: "Sunlight Financial",
  warranty_description: "15-year workmanship warranty on all roofing work. We stand behind everything we install.",
  emergency_available: true,
  emergency_description: "24/7 emergency roofing service for storm damage, leaks, and urgent repairs.",
  custom_faqs: [
    { q: "Do you offer warranties?", a: "Yes! All our work comes with a 15-year workmanship warranty. We also honor manufacturer warranties on all shingles." },
    { q: "How long does a roof replacement take?", a: "Most replacements take 3-5 business days depending on roof size and weather. We'll give you an exact timeline after inspection." },
    { q: "Can you work with my insurance?", a: "Absolutely. We work with insurance claims daily. Our team will document the damage and help with the claim process." },
  ],
  differentiators: "GAF Master Elite certified (top 2% of roofers nationwide), 15 years in business, 24/7 emergency service, 15-year workmanship warranty",
  rileyEnabled: true,
  completionPct: 100,
};

// ── Insights Page Fixtures ─────────────────────────────────────────────

export const DEMO_INSIGHTS = {
  scoreboard: {
    closedThisWeekCount: 2,
    closedThisWeekRevenue: 34000,
    pipelineCount: 4,
    pipelineValue: 68000,
    closeRatePct: 38,
    forecastRevenue: 25840,
  },
  moneyLeft: {
    totalEstimatedValue: 23000,
    leads: [
      { id: "demo-lead-001", name: "Marcus Johnson", estimateLow: 14000, estimateHigh: 18000, estimateMaterial: "Standing Seam Metal", heatScore: 82, hoursSinceCreated: 3, widgetViews: 6, reason: "Heat 82 · viewed 6× · not contacted" },
      { id: "demo-lead-008", name: "Karen White", estimateLow: 6000, estimateHigh: 9000, estimateMaterial: null, heatScore: 28, hoursSinceCreated: 72, widgetViews: 0, reason: "3d+ no contact" },
    ],
  },
  homeownersWant: {
    totalConvos: 47,
    questions: [
      { type: "price_seeking", label: "Pricing", count: 16, pct: 34 },
      { type: "general_info", label: "General Info", count: 10, pct: 22 },
      { type: "timeline_seeking", label: "Timeline", count: 8, pct: 18 },
      { type: "insurance", label: "Insurance", count: 6, pct: 12 },
      { type: "trust_seeking", label: "Warranty & Trust", count: 4, pct: 8 },
      { type: "scheduling", label: "Scheduling", count: 3, pct: 6 },
    ],
    topMaterial: { name: "Architectural Shingle", pct: 46 },
    financingInterestPct: 64,
  },
  speedGame: {
    avgReplyMinutes: 124,
    fastestCloses: { minutes: 22, count: 2 },
    buckets: [
      { label: "fast", range: "< 30 min", leadCount: 5, closedCount: 3, closeRatePct: 60 },
      { label: "mid", range: "30m – 2h", leadCount: 4, closedCount: 1, closeRatePct: 25 },
      { label: "slow", range: "2h+", leadCount: 6, closedCount: 1, closeRatePct: 17 },
    ],
    totalContacted: 15,
  },
  rileyROI: {
    state: "first_close" as const,
    convoCount: 47,
    leadsCaptured: 13,
    pipelineValue: 48000,
    wonCount: 1,
    wonRevenue: 21000,
    roiMultiplier: 141,
  },
  reviewMomentum: {
    newThisMonth: 4,
    totalReviewed: 5,
    totalSent: 12,
    clickRatePct: 67,
    reviewRatePct: 42,
    unrequestedCompleted: 1,
    recentReviewed: [
      { leadName: "Tom Henderson", sentAgo: "2w ago" },
      { leadName: "Kevin Nguyen", sentAgo: "3w ago" },
    ],
  },
  customerDNA: {
    wonCount: 3,
    unlocked: false,
    avgRoofAge: null,
    topMaterial: null,
    avgHomeValue: null,
    avgWidgetViews: null,
    newHomeownerPct: null,
    financingPct: null,
  },
};

// ── Estimate Settings (pre-filled pricing) ─────────────────────────────

export const DEMO_ESTIMATE_SETTINGS = {
  asphalt_low: "8000",
  asphalt_high: "14000",
  metal_low: "12000",
  metal_high: "18000",
  tile_low: "18000",
  tile_high: "28000",
  flat_low: "6000",
  flat_high: "10000",
  service_zips: ["33602", "33606", "33609", "33701", "33755", "34205"],
  weather_surge_enabled: false,
  buffer_pct: "10",
};

// ── Business Profile (settings page) ───────────────────────────────────

export const DEMO_PROFILE = {
  business_name: DEMO_BUSINESS_NAME,
  phone: "(813) 555-0192",
  email: "info@summitroofing.com",
  city: "Tampa",
  state: "FL",
  zip: "33602",
  tagline: "Your Roof. Done Right.",
  logo_url: "",
  years_in_business: 15,
  license_number: "CCC1234567",
  warranty_years: 15,
  is_licensed: true,
  is_insured: true,
  gaf_master_elite: true,
  owens_corning_preferred: true,
  certainteed_select: false,
  bbb_accredited: true,
  bbb_rating: "A+",
  crm_connected: "jobber",
  crm_status: "connected",
};

// ── Addons (for estimate settings) ─────────────────────────────────────

export const DEMO_ADDONS = [
  { id: "demo-addon-1", name: "Ridge Vent Upgrade", description: "Improved attic ventilation", price: 850 },
  { id: "demo-addon-2", name: "Ice & Water Shield", description: "Extra leak protection at eaves and valleys", price: 1200 },
  { id: "demo-addon-3", name: "Gutter Guard System", description: "Leaf protection for all gutters", price: 1500 },
];
