// Vault registry — knowledge entries from Skool community, frameworks, and research.
// Add new entries here and they'll appear on the LEARN tab automatically.

export interface VaultEntry {
  id: string;           // Unique entry ID (e.g., "031", "skool-2026-04-05")
  title: string;        // Entry title
  speaker: string;      // Who taught/presented this
  source: string;       // "skool" | "research" | "book" | "other"
  date: string;         // YYYY-MM-DD when processed
  hook: string;         // One-line summary — the "why this matters"
  summary: string[];    // Bullet point summary (3-5 bullets)
  details: string[];    // Detailed bullet points (key takeaways, frameworks, specifics)
  diagram?: string;     // ASCII/text diagram or Mermaid syntax (optional)
  links: { label: string; href: string }[];  // Related links (vault entries, features, external)
  tags: string[];       // Categorization tags
  featured: boolean;    // Show in Key Frameworks section
  revenuePlay?: string; // If this maps to a specific revenue play, describe it
}

// ─── All vault entries — newest first ──────────────────────────

export const VAULT_ENTRIES: VaultEntry[] = [
  // ── Recent Entries ──────────────────────────────────────────
  {
    id: "065",
    title: "GTM Engineering: Agent Jockeying & Autonomous Marketing with Claude Code",
    speaker: "Greg Isenberg + Cody Schneider",
    source: "other",
    date: "2026-04-04",
    hook: "Run 10+ Claude Code instances simultaneously — bulk generate ads, auto-manage campaigns, scrape LinkedIn engagers, cold email podcast hosts — all from one folder with API keys. The middle work disappears.",
    summary: [
      "GTM engineering = using Claude Code as an agent harness to automate all marketing/sales middle work via APIs (Facebook Ads, Instantly, Phantom Buster, Apollo, etc.)",
      "Agent jockeying: run 10+ Claude Code windows simultaneously, each doing a different marketing task. Context-switch between them like managing a team",
      "Bulk ad creative generation: React components → HTML-to-canvas → PNGs. Infinite variations at zero marginal cost. Upload directly to Facebook via API",
      "Autonomous ad optimization loop: pull performance data → pause high-CPM losers → promote winners to dedicated ad sets → run on daily cron via Railway",
      "LinkedIn engagement scraping pipeline: post URL → Phantom Buster extracts engagers → Apollo enriches → Million Verifier → Instantly cold email campaign",
    ],
    details: [
      "Setup: create a master folder (e.g., 'growth-agents/') with .env file holding ALL API keys (Instantly, HubSpot, Facebook Ads, Perplexity, Million Verifier, Phantom Buster, Apollo, etc.). This becomes your workspace for all agent work",
      "Software evaluation shift: 'How robust is the API?' is now the #1 buying criteria. Salesforce beats HubSpot for AI foundation because of richer API. If you can't do it via API, the tool is becoming obsolete",
      "Bulk Facebook ad workflow: (1) Use Perplexity API to scrape Reddit/Twitter for ICP pain points, (2) Generate ad variations as React components with text from pain points, (3) Download as PNGs via HTML-to-canvas, (4) Bulk upload to Facebook ad set via API, (5) Build tracking dashboard, (6) Agent analyzes CPM data and pauses losers",
      "LinkedIn engagement → cold email pipeline: (1) Drop LinkedIn post URL in Slack, (2) Phantom Buster API extracts all engagers, (3) Apollo API enriches with email/company, (4) Million Verifier validates emails, (5) Auto-add to Instantly campaign. Entire flow triggered from one Slack message",
      "Podcast outreach automation: Rephonic API scrapes podcast host emails in target category → Million Verifier → Instantly campaign → agent responds to replies to book appearances. Cody's Instantly inbox was full of booking replies",
      "On-demand infrastructure: Railway API spins up Postgres databases on the fly for one-time analysis, then spins down. On-demand UIs, on-demand databases = the future of personal software",
      "Notion document generation: Claude Code creates giveaway docs, lead magnets, and assets following existing templates in the repo. 'Create a notion document based off our current structure'",
      "Key insight on ad creative: React component ads cost nothing (vs Nano Banana ~10 cents each). Use code-generated ads to find winning ANGLES and MESSAGING first, then upgrade to high-quality image generation for proven winners",
      "Domain vocabulary as moat: 'Just because it can be built doesn't mean you can build it because you don't have the vocabulary.' A 20-year graphic designer describes texture in one sentence that one-shots the output. Hannah's roofing vocabulary = unfair advantage",
      "Agent swarms in practice: specific jobs-to-be-done workflows, not generic 'give AI access to everything.' Each agent has a narrow lane → deploy to Railway server → runs in perpetuity",
      "Data pipeline > MCP for analytics: MCP connections to Facebook Ads hit pagination limits — you only see 5% of data. Use a proper data warehouse (like Graph) synced continuously, then query via MCP for accurate analysis",
      "RuufPro application: (1) Bulk generate roofing ad creative from pain points in r/roofing and Facebook groups, (2) Auto-manage ad campaigns with daily optimization, (3) Scrape engagers from roofing LinkedIn posts → cold email, (4) Podcast outreach to contractor/home improvement shows, (5) Build internal dashboards for tracking all pipelines",
    ],
    diagram: "Master Folder (.env + skills) → Claude Code Instance 1: LinkedIn Responder | Instance 2: Bulk Ad Generator (Perplexity → React → PNG → Facebook API) | Instance 3: Podcast Scraper (Rephonic → Verify → Instantly) | Instance 4: LinkedIn Scraper (Phantom Buster → Apollo → Verify → Instantly) | Instance 5: Ad Analyzer (Graph MCP → Pause Losers → Promote Winners) | Railway: Deploy any instance as persistent agent",
    links: [
      { label: "Related: Cold Email at Scale", href: "/mission-control/vault/033" },
      { label: "Related: Keyword-to-Lead Pipeline", href: "/mission-control/vault/057" },
      { label: "Related: Perplexity Research Emails", href: "/mission-control/vault/059" },
      { label: "Related: Video Outreach System", href: "/mission-control/vault/058" },
    ],
    tags: ["gtm-engineering", "claude-code", "agent-jockeying", "facebook-ads", "linkedin", "podcast", "automation", "railway", "instantly", "phantom-buster"],
    featured: true,
    revenuePlay: "RuufPro's entire outreach stack automated: (1) Bulk ad creative from roofer pain points at zero cost, (2) Autonomous ad optimization on daily cron, (3) LinkedIn post engagers → cold email pipeline, (4) Podcast booking for authority. All running from one growth-agents folder with Claude Code instances.",
  },
  {
    id: "064",
    title: "Firecrawl: The Web Data Layer for AI Agents",
    speaker: "Greg Isenberg",
    source: "other",
    date: "2026-04-04",
    hook: "One API call replaces custom scrapers. Firecrawl gives AI agents eyes and hands on the internet. Clean structured data is the new oil — the most valuable software products will use scraping at the backbone.",
    summary: [
      "Firecrawl = one API call to scrape any website and get back clean markdown, structured JSON, screenshots. Feed to any AI model. Three lines of code",
      "6 superpowers: scrape (one page), crawl (entire site), map (all URLs), search (Google + full content), agent (describe data, it finds it), browser (AI controls real browser)",
      "The AWS moment for web data: in 2006 AWS eliminated server management, in 2026 Firecrawl eliminates scraper management. One API call replaces thousands of lines of code",
      "Niche vertical > horizontal: don't build another SEMrush. Build 'SEO audits for dentists only' or 'Amazon FBA seller review tracker.' Charge $99-500/mo for what incumbents charge $1000+",
      "The 5-layer AI agent stack: agent harness (Claude Code) → search layer (Perplexity) → web data layer (Firecrawl) → ops brain (Notion/Obsidian) → outbound + audience (Instantly/Apollo)",
    ],
    details: [
      "Traditional scraping: custom scraper per site, manage proxies, handle anti-bot, parse messy HTML, scripts break when sites change. Firecrawl: one API call, proxies built in, anti-bot built in, AI handles layout changes",
      "Browser sandbox: secure AI-controlled browser that fills forms, clicks buttons, handles login/auth, navigates pagination. Watch live as AI browses. Stay logged in across sessions",
      "Agent endpoint: type a natural language prompt → Firecrawl agent searches web → clicks through pages → extracts data → returns structured JSON. Example: 'Find all YC Winter 24 dev tool companies with founders and emails'",
      "Startup idea framework: (1) Pick a niche, (2) Build scraper with Firecrawl, (3) Package output (CSV, dashboard, Slack alert, API), (4) Sell the OUTPUT not the tool ($500-5K/mo per client), (5) Automate with cron jobs",
      "Niche product ideas: price monitoring for sneaker resellers ($500/mo), SEO gap finder for dentists ($200/mo), remote AI/ML job aggregator ($29/mo), crypto token due diligence ($5K/mo to VCs), real estate comp report agent ($300/mo), Amazon review intelligence ($99/mo)",
      "Lead gen as a service: client gives 50 company names → Firecrawl agent finds founders and emails → deliver enriched CSV → charge $100-500 per batch. Cost: ~$2 in Firecrawl credits. 95%+ margin",
      "Firecrawl pricing: free tier available, agent gives 5 free runs/day, scrape = 1 credit, crawl = 1 credit per page. Very affordable at scale",
      "Key insight: 'Incumbents charge hundreds/month for generic tools. Your version charges $20-70/month for a tool that does one thing perfectly for one customer.' Constellation Software ($75B) built on this exact principle — hundreds of vertical software companies",
      "IdeaBrowser.com example: uses Firecrawl for trend data scraping → became #1 startup ideas/trends product. Proof that web data layer + AI + niche = defensible product",
      "RuufPro application: (1) Firecrawl as alternative/complement to Apify for competitor monitoring, (2) Scrape roofer websites to auto-generate demo sites, (3) Monitor Google Business Profile changes, (4) Build 'roofing SEO audit' free tool that scrapes prospect's site and grades it",
    ],
    diagram: "Builder → AI Agent (Claude/GPT brain) → MCP Protocol (nervous system) → Firecrawl (eyes + hands) → Internet → Clean Data (markdown/JSON/screenshots) → Wrap around product → Sell to niche",
    links: [
      { label: "Related: Apify Masterclass", href: "/mission-control/vault/029" },
      { label: "Related: Keyword-to-Lead Pipeline", href: "/mission-control/vault/057" },
      { label: "Related: Enterprise AI Architecture", href: "/mission-control/vault/056" },
    ],
    tags: ["firecrawl", "scraping", "web-data", "ai-agents", "infrastructure", "vertical-saas", "niche", "api"],
    featured: true,
    revenuePlay: "Firecrawl enables RuufPro's data moat: (1) Auto-scrape competitor roofer websites for demo generation, (2) Build a free 'Roofing Website Grader' tool that scrapes and scores any roofer's site, (3) Competitor monitoring as a Growth tier feature. The scraping layer makes our audit and outreach tools 10x more powerful.",
  },
  {
    id: "063",
    title: "7 Distribution Strategies for Vibe-Coded SaaS Products",
    speaker: "Greg Isenberg",
    source: "other",
    date: "2026-04-04",
    hook: "Code is commoditized. Distribution is the new moat. Seven strategies to get customers to your vibe-coded product — from MCP servers as sales teams to buying newsletters for $5K.",
    summary: [
      "The great flip: distribution people > product people > developers. 200K new vibe-coded projects/day on Lovable alone. Almost none get seen. Peter Levels: $3M+ revenue, zero employees, 750K followers + great SEO",
      "Distribution first, product second. Always. Smart builders grow audience to 1K → ask what they need → build in a weekend → launch to warm audience → iterate with real users → make money",
      "Seven strategies: (1) MCP servers as sales team, (2) Programmatic SEO (10K pages), (3) Free tool as top-of-funnel, (4) Answer Engine Optimization (AEO), (5) Viral artifacts, (6) Buy a niche newsletter, (7) AI content repurposing engine",
      "AEO is where SEO was in 2010. First movers will own niches for years. Peter Levels: AI referrals jumped 4% → 20% in one month",
      "The tool IS the marketing. Vibe code a free tool in a day, ship by lunch, it markets itself forever. Think 'free tool calendar' not just 'content calendar'",
    ],
    details: [
      "Strategy 1 — MCP Server as Sales Team: (1) Identify what question your product answers, (2) Build MCP server that returns that data (24hrs), (3) Publish to Smithery, MCPT, Open Tools registries, (4) Every AI assistant that connects sells for you 24/7. Example: 150+ installations in 30 days, $0 ad spend. 'Building MCP in 2026 = building for mobile in 2010'",
      "Strategy 2 — Programmatic SEO: Pick keyword pattern (e.g., '[service] in [city]'), build dataset with Firecrawl/scraping, create Next.js page template, generate AI content per page (NOT just variable swaps — actual unique paragraphs), publish 100 pages as MVP. Math: 10K pages × 30 visits/month × 2% conversion × $10 = $60K/month",
      "Strategy 3 — Free Tool as Top-of-Funnel: Build a grader/analyzer/calculator. User gets instant value ('your site scores 43/100'). Capture email to access results. User shares score = social proof + backlinks. Upsell to paid product. Ahrefs backlink checker = perfect example. 'Vibe code a free tool in a day, ship by lunch, it markets itself forever'",
      "Strategy 4 — Answer Engine Optimization (AEO): (1) Google top 20 questions your customer asks, (2) Write definitive structured answers — clear, direct, citation-worthy (not 3K-word fluff), (3) Add schema markup + FAQ blocks, (4) Publish on domain with authority, (5) Monitor Perplexity/ChatGPT citations with Otterly or Profound. Zero-click searches growing = AEO matters more than SEO",
      "Strategy 5 — Viral Artifacts: Ask 'what does my user want to brag about?' then make it beautiful + shareable. Examples: Spotify Wrapped (100M shares/year), GitHub contribution graph, Stripe Atlas incorporation milestone, Duolingo streak. Your logo subtle but present. Add share button that prefills the post. Every share = free impressions to exact target audience. Works in B2B too (Slack/Teams sharing)",
      "Strategy 6 — Buy a Niche Newsletter: Buy 5-50K subscriber newsletter for $5-20K on Duuce.com or Newsletter Investor. Many owners making $0-500/mo, happy to sell. You inherit trust from day one. Plug in your product immediately. It's a direct channel you OWN — can't be suppressed by algorithm changes. Repeat across niches",
      "Strategy 7 — AI Content Repurposing Engine: Record one 30-min pillar piece (podcast, video, voice memo). Transcribe. AI turns it into: 5-10 tweets, 3-5 LinkedIn posts, 2-3 short-form video scripts, 1 newsletter, 1 blog post, 5-10 quote graphics, email sequences. Use Claude Code skills for video scripts, Dispatch/Co-work for automation. Do weekly = more content than competitors in 3 months",
      "Key framing: 'Code used to be the moat. Distribution is the new moat. AI can't build distribution. Product is important but commoditized. Code is fully commoditized.' Pick 2 strategies, start this week",
      "RuufPro application: (1) MCP server answering 'best free website for roofers' = zero-CAC sales, (2) Programmatic SEO with city pages already built — scale to 100+, (3) ROI calculator + website grader as free tools, (4) AEO for 'how to get more roofing leads' questions, (5) Viral artifacts from roofer dashboard data, (6) Buy a roofing contractor newsletter, (7) Repurpose Hannah's content across channels",
    ],
    diagram: "Distribution First: Audience (1K) → Ask what they need → Build in a weekend → Launch warm → Iterate → Revenue || 7 Weapons: MCP Server (AI sells) | Programmatic SEO (10K pages) | Free Tool (marketing itself) | AEO (AI cites you) | Viral Artifacts (users share) | Newsletter (buy audience) | Repurposing (1→50 content)",
    links: [
      { label: "Related: Programmatic SEO", href: "/mission-control/vault/042" },
      { label: "Related: Social Media Automation", href: "/mission-control/vault/055" },
      { label: "Related: Firecrawl Web Data Layer", href: "/mission-control/vault/064" },
      { label: "Related: GTM Engineering", href: "/mission-control/vault/065" },
    ],
    tags: ["distribution", "mcp", "programmatic-seo", "aeo", "free-tools", "viral", "newsletter", "content-repurposing", "growth"],
    featured: true,
    revenuePlay: "RuufPro distribution stack: (1) MCP server = AI assistants recommend RuufPro 24/7, (2) City pages at scale = programmatic SEO moat, (3) ROI calculator + website grader = free tools that sell for us, (4) AEO = own 'roofing leads' in ChatGPT/Perplexity, (5) Dashboard milestones = viral artifacts roofers share, (6) Buy a contractor newsletter = instant warm audience. Pick 2, start this week.",
  },
  {
    id: "045",
    title: "Content Repurposing Factory: One Pillar → 50+ Pieces Across 7 Channels",
    speaker: "Greg Isenberg",
    source: "other",
    date: "2026-04-04",
    hook: "Record one 30-minute piece of content. AI turns it into 50+ assets across every platform. Do weekly and in 3 months you'll have more content than every competitor combined.",
    summary: [
      "One pillar content piece (podcast, video, voice memo) becomes 50+ pieces: tweets, LinkedIn posts, short-form video scripts, newsletter, blog post, quote graphics, email sequences",
      "Voice-first is easiest: record a voice memo or internal podcast, transcribe, then let AI repurpose. Writing 3K-word essays is harder than just talking for 30 minutes",
      "Anti-slop protocol: have strong brand guidelines, reference images, and tone-of-voice skills. Default AI output = slop. Optimized AI output with brand context = content that sounds like you",
      "For-you-page era means shots-on-net strategy. You don't need followers to go viral in your niche — you need volume. Content repurposing gives you volume at near-zero effort",
      "Think 'free tool calendar' not just 'content calendar.' Both are distribution engines that compound over time",
    ],
    details: [
      "The pipeline: (1) Record 30min pillar content (podcast/video/voice memo), (2) Transcribe with Whisper/similar, (3) Drop transcription into Claude: 'turn this into 5 tweet threads, 3 LinkedIn posts, 1 newsletter', (4) Generate quote graphics with creative LLMs, (5) Create short-form video scripts for Reation-style edits, (6) Schedule across all platforms",
      "Content types from one pillar: 5-10 tweets/threads, 3-5 LinkedIn posts, 2-3 short-form video scripts, 1 newsletter edition, 1 blog post, 5-10 quote graphics, email sequences for nurture campaigns",
      "Tools: Claude Code skills for video scripts, Claude Dispatch/Co-work for automation, OpenClaw for workflow orchestration, Super Whisper for transcription, creative LLMs for graphics",
      "Anti-slop requirements: (1) Strong brand identity and reference images, (2) Tone-of-voice documentation, (3) Claude Code skills with brand context baked in, (4) Human review pass — especially for LinkedIn/newsletter where voice matters most",
      "Compounding math: 1 pillar/week × 50 pieces = 200 pieces/month. In 3 months = 600 pieces of content. Your competitors are putting out maybe 10/month. 60x content advantage",
      "RuufPro application: Hannah records voice memo about roofing contractor pain points or RuufPro features → content-repurposer agent turns it into 50+ pieces → scheduled across LinkedIn, Twitter, Facebook groups, email, blog. Builds authority as 'the person helping roofers get online'",
    ],
    diagram: "Pillar Content (30min) → Transcribe → AI Repurposer → 5-10 Tweets | 3-5 LinkedIn Posts | 2-3 Video Scripts | 1 Newsletter | 1 Blog Post | 5-10 Graphics | Email Sequences → Schedule Across Platforms → Compound Weekly",
    links: [
      { label: "Related: Social Media Automation", href: "/mission-control/vault/055" },
      { label: "Related: 7 Distribution Strategies", href: "/mission-control/vault/063" },
    ],
    tags: ["content-repurposing", "distribution", "automation", "content-calendar", "social-media", "newsletter"],
    featured: false,
    revenuePlay: "Content repurposing builds Hannah's personal brand as the roofing SaaS expert. 600 pieces/quarter across all platforms. Authority → trust → inbound leads → lower CAC. The content-repurposer agent makes this a 30-min/week commitment instead of a full-time job.",
  },
  {
    id: "062",
    title: "$300K/mo: AI Chrome Extension + Skool Community Model",
    speaker: "Jack Roberts",
    source: "skool",
    date: "2026-04-03",
    hook: "Chrome extension co-pilot + Skool community + Make.com backend = software lock-in + recurring revenue. Member hit $315K in one month.",
    summary: [
      "Build an AI Chrome extension that follows users around the web as a co-pilot (copywriter, researcher, content creator)",
      "Gate access behind monthly Skool community subscription with rotating access keys — simple Make.com router check",
      "OpenAI Assistants with custom knowledge docs make output uniquely valuable vs generic ChatGPT wrappers",
      "Free Skool community → trust → paid group with Chrome extension access. 'Death of the subscriber' — 1,000 true followers > 100K vanity.",
    ],
    details: [
      "6-step roadmap: (1) Pick growth problem, (2) Launch Chrome extension, (3) Build Make.com automation, (4) Start free Skool community, (5) Drive traffic from ONE platform, (6) 'Whale hunting' for premium clients",
      "'Elaborate' example: browse any webpage → add thoughts + select platform (LinkedIn/IG/X/email) → AI generates copy in your tone of voice using page context + custom training data",
      "Make.com flow: webhook receives all data → router checks elaborateKey → denied path returns 'subscribe' message → accepted path hits OpenAI Assistant → returns platform-specific copy to extension",
      "Software lock-in > content lock-in: members who use your Chrome extension daily are 10x stickier than course-watchers",
      "Monthly key rotation: simple string check (e.g., 'elaborate2024'), changes monthly. No key = extension returns subscribe link.",
      "10 Chrome extension ideas provided: to-do refresher, video assistant, document analyzer, lead-gen helper, workflow integrator, YouTube summarizer, email assistant, web scraper, content calendar, video-to-content pipeline",
      "OpenAI platform.openai.com: create Assistant → upload training docs (copywriting books, niche knowledge) → enable file search → instant domain-expert AI",
      "Community members hitting $55-60K/mo just from LinkedIn content → free Skool → paid group pipeline",
      "RuufPro parallel: the free website IS the 'free community' — proves value, builds trust, then upsells to $149/mo. Mission Control dashboard IS the software lock-in.",
    ],
    diagram: "Chrome Extension (any webpage) → Make.com Webhook → Router: [Key Valid?] → YES: OpenAI Assistant (custom knowledge + tone + platform) → Webhook Response (copy) → Extension displays result | NO: 'Subscribe' message + community link",
    links: [
      { label: "Related: Social Media Telegram Bot", href: "/command-center/vault/055" },
      { label: "Related: Selling Software Not Automations", href: "/command-center/vault/010" },
    ],
    tags: ["chrome-extension", "skool", "community", "make.com", "software", "recurring-revenue", "content"],
    featured: false,
    revenuePlay: "RuufPro's free site = free Skool community equivalent. Mission Control = software lock-in. The pattern: give value free → build trust → upsell paid tier with features they now depend on daily.",
  },
  {
    id: "061",
    title: "AI Image Generation + Personalized Visual Outreach (Nano Banana)",
    speaker: "Jack Roberts",
    source: "skool",
    date: "2026-04-03",
    hook: "Scrape leads → AI generates unique branded images per prospect (logo on cereal bowl, cap, etc.) → hyper-personalized visual outreach that no one else is sending. ~10 cents/image.",
    summary: [
      "Use Nano Banana Pro via API to generate custom branded images for every lead — their logo/name inserted into creative scenes (cereal bowls, caps, noodles, phones)",
      "Full pipeline: Apify Leads Finder → Airtable with AI field agent (auto-generates image prompts per lead) → n8n/Make.com calls Nano Banana API → uploads result back to Airtable",
      "Face swapping for thumbnails/content: upload reference image + your photo → AI places you in the scene with matching facial expressions. Built as a Google AI Studio app.",
      "~10 cents per generation. Pattern-interrupting visual outreach that doubles response rates vs text-only emails.",
    ],
    details: [
      "Pipeline: Apify Leads Finder (scrape by niche, location, job title) → export CSV → import to Airtable → AI Field Agent generates custom image prompt per lead using company description → n8n triggers Nano Banana API via Krea.ai → polls for completion → downloads image → uploads to Airtable row",
      "Image hosting: use ImageBB as intermediary to host reference images before sending to Nano Banana API",
      "Krea.ai marketplace provides the Nano Banana API endpoint. Free credits to start, ~10 cents per generation at scale.",
      "JSON prompt technique: use ChatGPT to reverse-engineer a reference image into a structured prompt, then make ONE variable dynamic (company name/logo). Same creative concept, unique per lead.",
      "Airtable AI Field Agent: built-in feature that runs GPT on each row automatically. Set prompt template with company_name + company_description variables → auto-generates unique image prompts for every lead.",
      "n8n loop pattern: call API → wait/poll for completion status → download when 'completed' → upload to Airtable attachment field. Handles rendering delays gracefully.",
      "Google AI Studio app: built a 'Thumb Studio AI' that takes a viral thumbnail + your photo → places you in the image with matching expression. Native Nano Banana integration, no webhook needed.",
      "Creative applications: cereal bowl with logo ('we eat your competition for breakfast'), phone with notifications (new lead alerts), person wearing branded cap, custom YouTube thumbnails",
      "Apify Leads Finder cost: 22 cents for 100 leads with full contact info (name, email, company, LinkedIn, description). Combine with image gen for total outreach cost of ~$10 per 100 leads.",
      "RuufPro application: generate before/after images of roofer websites. 'Here's what [Roofer Name] Roofing could look like online' with their actual business name on a beautiful RuufPro template screenshot. Visual proof in the cold email.",
    ],
    diagram: "Apify Leads Finder → CSV → Airtable (AI Field Agent: generate prompts) → n8n: [Nano Banana API via Krea.ai] → [Poll for completion] → [Download image] → [Upload to Airtable] → Email campaign with personalized images",
    links: [
      { label: "Related: Text-to-Video Outreach", href: "/command-center/vault/058" },
      { label: "Related: Keyword-to-Lead System", href: "/command-center/vault/057" },
      { label: "Related: Mass Email with Perplexity", href: "/command-center/vault/059" },
    ],
    tags: ["lead_gen", "automation", "images", "outreach", "nano_banana", "n8n", "personalization", "creative"],
    featured: false,
    revenuePlay: "For RuufPro outreach: AI-generate a 'before/after' image for each roofer prospect. Left side: their current (bad/missing) website. Right side: a beautiful RuufPro template with their name on it. Attach to cold email. Visual proof > text claims.",
  },
  {
    id: "060",
    title: "AI Lead Qualification & Scoring Engine",
    speaker: "Jack Roberts",
    source: "skool",
    date: "2026-04-03",
    hook: "Lead magnet form → Make.com scores leads with deterministic code (not probabilistic AI) → tiered prioritization → CRM. Call the gold-tier leads first, let automation handle the rest.",
    summary: [
      "Smart lead magnets capture qualifying data (employees, revenue, dream outcome) not just name+email — pre-qualify before any human touches the lead",
      "Deterministic scoring via Make.com code module beats AI scoring — same inputs always produce same tier. Reliable, not random.",
      "Lead tiers: Gold/Silver/Bronze based on weighted scoring matrix (revenue weight > employee count weight > recency weight). Focus human time on Gold only.",
      "Speed to lead is killer — the system can trigger instant call/email to Gold leads while Silver/Bronze enter automated sequences",
    ],
    details: [
      "Pipeline: Paperform/Typeform lead magnet → Make.com webhook → Send custom email with lead magnet → Code module scores lead → Google Sheets/CRM with tier + action step",
      "Scoring matrix example: 1-10 employees = 10pts, 11-50 = 20pts, 51-250 = 30pts, 251+ = 40pts. Turnover: <$100K = 10pts, $100K-$500K = 20pts, $500K-$1M = 30pts, $1M+ = 40pts.",
      "Weighted scoring: multiply employee score by 0.3, turnover by 0.5, recency by 0.2. Total determines tier.",
      "Key insight: DETERMINISTIC vs PROBABILISTIC. AI (LLMs) are probabilistic — same input can give different scoring each time. The code module is deterministic — same input ALWAYS gives same output. Use code for scoring, AI for writing.",
      "Warmth factor: track 'last contacted' date. 48hrs = hot, 1 week = warm, 2 weeks = cooling, 4+ weeks = cold, 6+ months = archive. Re-engagement triggers automatically.",
      "Lead magnet design matters: ask questions that MAP to your scoring variables. Don't ask 'what's your biggest challenge' — ask 'what's your annual revenue' because that's scorable.",
      "The form IS the qualification. By the time someone submits, you already know their tier before any human reads it.",
      "Action steps per tier: Gold = instant phone call + personal email, Silver = automated email sequence + Loom video, Bronze = nurture sequence only",
      "RuufPro application: lead magnet = 'Get Your Free Roofing Website.' Form asks: How many jobs/month? Have a website? Get leads online? Annual revenue range? Score determines: Free tier only, or fast-track to Pro upsell after site goes live.",
    ],
    diagram: "Lead Magnet Form → Make.com Webhook → [Send Lead Magnet Email] → [Code Module: Score Lead] → Google Sheets/CRM (Name, Email, Score, Tier, Action Step) → Gold: Instant Call | Silver: Auto Sequence | Bronze: Nurture",
    links: [
      { label: "Related: Mass Email with Perplexity", href: "/command-center/vault/059" },
      { label: "Related: Keyword-to-Lead System", href: "/command-center/vault/057" },
      { label: "Related: $100M Offers Pricing", href: "/command-center/vault/031" },
    ],
    tags: ["lead_gen", "qualification", "scoring", "automation", "make.com", "CRM", "sales_funnel"],
    featured: false,
    revenuePlay: "RuufPro onboarding IS the lead magnet. The 4-field form (name, phone, city, design style) already qualifies. Add 2 questions: 'How many jobs/month?' and 'Do you currently get leads from your website?' Score determines upsell timing and tier.",
  },
  {
    id: "059",
    title: "Mass Personalized Email with Perplexity Research",
    speaker: "Jack Roberts",
    source: "skool",
    date: "2026-04-03",
    hook: "Scrape 1000 leads → Perplexity researches each one → GPT writes 1-of-1 email citing their awards/news → HTML email with signature in Gmail draft. The full cold email pipeline.",
    summary: [
      "Scrape 1000+ niche websites via Apify → get contact emails via Contact Info Scraper → Perplexity researches 10 facts about each business → GPT writes unique email + subject line → Gmail draft",
      "Perplexity AI replaces manual research — finds recent awards, news, Trustpilot scores, years in business. Makes every email feel hand-researched.",
      "Email format is brutally short: 'Hey [name], love what you're doing at [company]. [1 personalized line]. We've helped similar businesses increase sales by 70%. Can I send a 3-min Loom?'",
      "Human-in-the-loop: all drafts land in Google Sheets/Gmail for review before sending. Quality control without manual work.",
    ],
    details: [
      "Pipeline: Apify Google scraper (1000 results) → ChatGPT extracts URLs to .txt → Apify Contact Info Scraper (bulk upload .txt of URLs) → Airtable populates: company, email, website → Make.com triggers per row",
      "Make.com flow: HTTP get website → HTML-to-text → Claude/GPT summarizes in 35 words + 5 bullet features → Perplexity API researches 10 facts (awards, news, Trustpilot, years in biz) → GPT writes HTML email with signature → GPT writes subject line → Gmail draft",
      "Perplexity prompt: 'Uncover 10 fascinating facts about [URL]. Dive deep into reliable external sources. Well-sourced, up-to-date (last 12 months), data-driven, business-relevant.'",
      "Email Bot prompt: Keep it SHORT. Max 2-sentence paragraphs. Start with 'Hey there'. Insert company name + 1 personalized line (max 20 words) referencing an achievement. End with asking permission to send a Loom video.",
      "Subject Line Bot: under 50 chars, curiosity-driven, reference specific fact from research if possible. No clickbait, no spam triggers.",
      "Website Summarizer: 35-word max summary + 5 bullet features with emojis. Used to quickly qualify and understand each prospect.",
      "Key insight from Jack: Claude's writing style is more conversational than GPT — better for emails that need to sound human. Uses Claude for email copy, GPT for data processing.",
      "Cost breakdown: Apify $5/mo free (covers ~1400 results), Claude/GPT ~$5 deposit, Perplexity API credits, Make.com free tier handles the orchestration. Total: ~$15-20 to process 1000 leads.",
      "HTML email template includes full email signature with photo, company name, socials (FB, Twitter, LinkedIn, Instagram), phone, website, address. Professional look beats plain text.",
      "RuufPro adaptation: instead of 'Can I send a Loom?', the email says 'I already built your website — here's the link.' The demo IS the value. No ask, just proof.",
    ],
    diagram: "Apify (scrape Google) → ChatGPT (extract URLs) → Apify (Contact Info Scraper) → Airtable → Make.com: [HTTP get site] → [HTML-to-text] → [Claude: Summarize] → [Perplexity: Research 10 facts] → [Claude: Write Email] → [GPT: Subject Line] → Gmail Draft",
    links: [
      { label: "Related: Keyword-to-Lead System", href: "/command-center/vault/057" },
      { label: "Related: Text-to-Video Outreach", href: "/command-center/vault/058" },
      { label: "Related: Cold Email at Scale", href: "/command-center/vault/033" },
    ],
    tags: ["lead_gen", "automation", "cold_email", "outreach", "perplexity", "make.com", "personalization", "research"],
    featured: true,
    revenuePlay: "Full RuufPro outreach pipeline: scrape 'roofing contractors [city]' → get emails → Perplexity finds their reviews/awards/years in biz → email says 'Congrats on [specific achievement]. I built you a free website — [preview link].' Highest personalization + strongest lead magnet.",
  },
  {
    id: "058",
    title: "Text-to-Video Personalized Outreach System",
    speaker: "Jack Roberts",
    source: "skool",
    date: "2026-04-03",
    hook: "Auto-generate personalized video outreach: scrape website → AI script → clone your voice → render video with their homepage scrolling in background. Pattern-interrupting at scale.",
    summary: [
      "Fully automated pipeline: input a URL → scrape + summarize website → AI writes 80-100 word personalized script → voice clone narrates → video renders with their homepage scrolling",
      "Solves the 'personalization vs scale' problem — video converts highest but takes longest to create manually. This makes it a cron job.",
      "Uses Make.com + Airtable + Anthropic Claude + ElevenLabs + Screenshot One + Creatomate for the full pipeline",
      "Every video is unique: references specific details from the prospect's website, uses YOUR cloned voice, shows THEIR homepage",
    ],
    details: [
      "Pipeline: Airtable trigger (name, URL, email) → HTTP get website → HTML-to-text → Claude summarizes in 35 words + 5 bullet features → Claude writes personalized 80-100 word script → ElevenLabs voice clone narrates → Screenshot One records scrolling homepage video → Creatomate composites audio + video + text overlay → Gmail draft or direct send",
      "Script structure: Opens with 'Hey there, it's [name]. I wanted to share one quick AI hack...' → References 2 specific website observations → Shares 1 relevant AI improvement idea → Closes with 'If you'd like more info, I'm happy to help.'",
      "Voice cloning via ElevenLabs — use YOUR own voice so when prospects reply, it actually sounds like you. Builds trust.",
      "Screenshot One: scrolling screenshot API that records the prospect's homepage as a video (up to 30 seconds). Free tier available. Parameterizable scroll speed/duration.",
      "Creatomate: video rendering API that composites audio (voice) + video (homepage scroll) + text overlays (prospect name). Free to start, credits-based.",
      "Key insight: an hour of prompt engineering is worth 10 hours of post-production. Train the script-writing AI on YOUR business data, best practices, case studies.",
      "Make.com 'sleep' module needed between render request and download — rendering takes time. Add 60-120 second delay.",
      "Google Drive used as intermediary storage for audio files before sending to Creatomate",
      "Jack uses Anthropic Claude Sonnet 3.5 instead of GPT — says text output is more conversational and natural-sounding for spoken scripts",
      "RuufPro application: instead of generic 'AI hack' pitch, send roofers a video showing THEIR current website (or lack thereof) next to a RuufPro-generated site with their name on it. 'Here's what your online presence could look like.' Devastating comparison.",
    ],
    diagram: "Airtable (name, URL, email) → [HTTP: Get Website] → [HTML-to-Text] → [Claude: Summarize] → [Claude: Write Script] → [ElevenLabs: Voice Clone] → [Google Drive: Store Audio] → [Screenshot One: Record Homepage] → [Creatomate: Render Video] → Gmail Draft / Send",
    links: [
      { label: "Related: Keyword-to-Lead System", href: "/command-center/vault/057" },
      { label: "Related: Cold Email at Scale", href: "/command-center/vault/033" },
      { label: "Related: ROI Calculator Close", href: "/command-center/vault/032" },
    ],
    tags: ["lead_gen", "automation", "video", "outreach", "voice_clone", "make.com", "personalization"],
    featured: true,
    revenuePlay: "Video outreach for RuufPro: record roofer's current (bad/missing) website scrolling on one side, RuufPro-generated site on the other. Voice clone says 'I built this for you, it's free to claim.' Highest possible conversion rate for cold outreach.",
  },
  {
    id: "057",
    title: "Keyword-to-Lead Autonomous Outreach System",
    speaker: "Jack Roberts",
    source: "skool",
    date: "2026-04-03",
    hook: "4-part Make.com pipeline: keyword → Google scrape → human approval → deep contact scrape → AI-personalized email. The exact blueprint for RuufPro's Acquire phase.",
    summary: [
      "Enter a keyword into Airtable → system searches Google, returns results, you approve/reject, it scrapes contact info and generates personalized outreach",
      "Human-in-the-loop at the approval stage prevents wasted API calls and bad outreach — you only scrape what you actually want to contact",
      "AI references specific website content (awards, specialties) to personalize every email — not generic templates",
      "4 scenarios in Make.com: Scrape Internet → Load Results → Grab Contact Info → Generate Outreach + Gmail Draft",
    ],
    details: [
      "Tools: Airtable (command center), Make.com (orchestration), Apify ($5/mo free tier — Google Search Scraper + Contact Info Scraper), OpenAI API (email gen), Gmail (drafts)",
      "Step 1: Airtable 'search term' table triggers Apify Google Search Scraper — parameterized by country, language, max results (5-50+)",
      "Step 2: Apify webhook fires on completion → Make.com fetches dataset → populates Airtable results table with title, URL, description",
      "Step 3: Human reviews results, marks 'Scrape' or 'Reject' — status change triggers Apify Contact Info Scraper on approved URLs",
      "Contact scraper grabs: email, phone, LinkedIn, Twitter, Instagram, Facebook, YouTube — all from one URL",
      "Step 4: Homepage HTML → GPT summarizes to plain English → GPT generates personalized subject line (<60 chars) + email body referencing specific achievements",
      "Email rules: <20 words/sentence, max 2-sentence paragraphs, casual tone, no jargon, start with 'Hey [Name]', end with 'Thanks'",
      "Subject line rules: under 60 chars, curiosity-driven, reference specific website detail if possible, no clickbait, no spam triggers",
      "RuufPro difference: instead of pitching a service call, we send a PRE-BUILT WEBSITE as the lead magnet — way more powerful than a generic cold email",
      "The Make.com blueprint JSON files are included — can be imported directly into Make.com via More → Import Blueprint",
      "Includes two GPT system prompts: 'Email Bot' for full email generation and 'Email 1-liner' for subject line generation",
    ],
    diagram: "Keyword → [Apify: Google Search] → Airtable Results → [Human: Scrape/Reject] → [Apify: Contact Scraper] → [GPT: Summarize Site] → [GPT: Write Email] → Gmail Draft + Airtable Contact Info",
    links: [
      { label: "Related: Local Lead Abundance", href: "/command-center/vault/005" },
      { label: "Related: Cold Email at Scale", href: "/command-center/vault/033" },
      { label: "Workflow: Roofer Discovery Pipeline", href: "/mission-control" },
      { label: "Workflow: Cold Email Sequences", href: "/mission-control" },
    ],
    tags: ["lead_gen", "automation", "scraping", "outreach", "make.com", "apify", "cold_email"],
    featured: true,
    revenuePlay: "Adapt this exact pipeline for RuufPro: keyword 'roofing contractors [city]' → scrape → approve → instead of cold email, auto-generate a preview site with their business name and send THAT as the lead magnet. 10x more compelling than a generic pitch.",
  },
  {
    id: "056",
    title: "Enterprise AI Architecture & AI Factories",
    speaker: "Onorio Padron",
    source: "skool",
    date: "2026-04-03",
    hook: "AI fails without operational model change. Productize your consulting — codify, diagnose, prescribe.",
    summary: [
      "Enterprise AI failing because companies implement point solutions without changing ops model",
      "3 AI Factory platforms will dominate: C3, Palantir, IBM Watson X",
      "Big data lakes are dead — virtualize data real-time from source via ontology layer",
      "Onorio productized his consulting: 76 drivers, 7 towers, $250K diagnostic → self-funding use cases",
    ],
    details: [
      "The Solow Paradox: tech benefits don't materialize without operational model redesign — happened with ERP, happening again with AI",
      "Companies buying per-department AI tools see no enterprise ROI — CEO sees millions spent, no aggregate benefit",
      "Data commoditization killed McKinsey's model — you can verify best practices in 15 minutes with AI now",
      "Shell runs 100+ use cases on C3, gets $1B/yr benefit, pays <1% to the platform",
      "Start with 15 top drivers + 2 use cases that each return $1.5M+ — payback in ~13 months",
      "RuufPro parallel: 'Digital Readiness Score' diagnostic that prescribes RuufPro as the fix",
      "Zero latency for roofers: missed call → lost $8K job. RuufPro = zero gap between need and lead capture",
    ],
    links: [
      { label: "Vault Entry 056", href: "/command-center/vault/056" },
      { label: "Related: Selling Software Not Automations", href: "/command-center/vault/010" },
    ],
    tags: ["enterprise", "architecture", "strategy", "consulting", "productization"],
    featured: false,
    revenuePlay: "Productize a 'Digital Readiness Score' for roofers — free diagnostic that prescribes RuufPro. Codify consulting like Onorio's 76-driver framework.",
  },
  {
    id: "055",
    title: "AI Social Media Automation (Telegram Bot)",
    speaker: "Jack",
    source: "skool",
    date: "2026-04-03",
    hook: "Voice/text → Telegram bot → AI orchestrator → platform-specific posts + AI images. Zero manual steps.",
    summary: [
      "Telegram bot as interface — voice or text message triggers full content pipeline",
      "AI orchestrator parses intent, routes to news research + content gen + image gen",
      "Platform-specific output for LinkedIn, X/Twitter, Instagram",
      "Replicate AI models generate custom images per post",
    ],
    details: [
      "No dashboard needed — conversational interface via Telegram",
      "News research layer makes posts timely and relevant, not generic",
      "Each platform gets tailored content: tone, length, hashtags, formatting",
      "End-to-end: idea → research → copy → image → publish with zero manual steps",
      "RuufPro opportunity: 'text us your job photos → we create a social post for you' as premium upsell",
      "Roofers hate creating content but know they need it — this removes all friction",
    ],
    links: [
      { label: "Vault Entry 055", href: "/command-center/vault/055" },
      { label: "Related: Content Repurposing Factory", href: "/command-center/vault/045" },
    ],
    tags: ["automation", "social-media", "content", "telegram", "ai-agents"],
    featured: false,
    revenuePlay: "Premium add-on: roofers text job photos to a bot → auto-generated social posts for Facebook/Instagram. $49-99/mo upsell.",
  },

  // ── Existing Key Frameworks (migrated from hardcoded) ────────
  {
    id: "031",
    title: "$100M Offers — Pricing Psychology",
    speaker: "Hormozi",
    source: "skool",
    date: "2026-01-15",
    hook: "Niching = 100x price. $149 bundle > $99 per feature.",
    summary: [
      "Niche down to charge premium — generic = commodity pricing",
      "Bundle features into a single offer, not à la carte",
      "$149 bundle beats $99/feature every time",
    ],
    details: [
      "The more specific your niche, the more you can charge — 'roofing websites' > 'contractor websites' > 'small business websites'",
      "Bundling creates perceived value that exceeds sum of parts",
      "Price anchoring: show the $299 tier first, $149 feels like a deal",
      "Never compete on price — compete on specificity and outcome",
    ],
    links: [
      { label: "Vault Entry 031", href: "/command-center/vault/031" },
      { label: "Pricing Strategy", href: "/command-center?tab=positioning" },
    ],
    tags: ["pricing", "hormozi", "strategy"],
    featured: true,
    revenuePlay: "Bundle at $149 > individual features at $99. Use niche specificity to justify premium.",
  },
  {
    id: "025",
    title: "Grand Slam Offer — Value Equation",
    speaker: "Hormozi",
    source: "skool",
    date: "2026-01-10",
    hook: "Dream outcome × likelihood ÷ (time delay × effort). Position as done-for-you.",
    summary: [
      "Value = (Dream Outcome × Perceived Likelihood) ÷ (Time Delay × Effort)",
      "Maximize top, minimize bottom — done-for-you wins",
      "RuufPro: instant site (low delay) + zero effort (done-for-you) = high value",
    ],
    details: [
      "Dream outcome: more roofing leads and jobs",
      "Perceived likelihood: show social proof, case studies, ROI calc",
      "Time delay: onboarding in 3 minutes, site live same day",
      "Effort & sacrifice: zero — we build it, they approve it",
      "Position every feature through this lens",
    ],
    links: [
      { label: "Vault Entry 025", href: "/command-center/vault/025" },
    ],
    tags: ["hormozi", "value-equation", "positioning"],
    featured: true,
  },
  {
    id: "005",
    title: "Local Lead Abundance System",
    speaker: "Jack",
    source: "skool",
    date: "2025-12-01",
    hook: "60K pre-scraped leads. Build sites as lead magnet, send via contact forms.",
    summary: [
      "60K+ roofing leads already scraped and ready",
      "Free site = the hook to get them in the door",
      "Outreach via contact forms at scale",
    ],
    details: [
      "Lead magnet is the free website itself — not a PDF or webinar",
      "Contact form outreach has 3x reply rate vs cold email to info@ addresses",
      "Target secondary cities first — less competition, same conversion",
      "Volume play: 1,000 contacts/day is the baseline",
    ],
    links: [
      { label: "Vault Entry 005", href: "/command-center/vault/005" },
      { label: "Outreach Pipeline", href: "/command-center?tab=outreach" },
    ],
    tags: ["leads", "outreach", "acquisition"],
    featured: true,
    revenuePlay: "Free site as lead magnet → outreach to 60K scraped leads → convert to $149/mo after value proven.",
  },
  {
    id: "023",
    title: "$40K/mo AI Sales",
    speaker: "James",
    source: "skool",
    date: "2026-01-05",
    hook: "ONE focused offer. Don't feature-sprawl. Sell the outcome.",
    summary: [
      "One offer, one outcome, one price — simplicity sells",
      "Feature sprawl kills conversions",
      "Sell the result (more roofing jobs), not the tool (website builder)",
    ],
    details: [
      "James hit $40K/mo by narrowing to a single AI service offering",
      "Every feature you add dilutes the message",
      "Roofers don't buy 'website + SEO + reviews + SMS' — they buy 'more jobs'",
      "The product page should read like a results guarantee, not a feature list",
    ],
    links: [
      { label: "Vault Entry 023", href: "/command-center/vault/023" },
    ],
    tags: ["sales", "focus", "positioning"],
    featured: true,
  },
  {
    id: "032",
    title: "ROI Calculator Close",
    speaker: "Andy Steuer",
    source: "skool",
    date: "2026-01-20",
    hook: "$32K/month in missed calls = $999/mo solution is obvious.",
    summary: [
      "Quantify the pain in dollars — make the ROI undeniable",
      "Missed calls × average job value = money left on table",
      "When the cost of inaction > your price, closing is easy",
    ],
    details: [
      "Average roofing job: $8-12K. Missing 3-4 calls/month = $32K+ lost",
      "ROI calculator on the sales page does the math for them",
      "Frame price as % of recovered revenue, not absolute cost",
      "'$149/mo to recover $32K/mo in missed opportunities'",
    ],
    links: [
      { label: "Vault Entry 032", href: "/command-center/vault/032" },
    ],
    tags: ["sales", "roi", "conversion"],
    featured: true,
    revenuePlay: "Build ROI calculator into sales flow. Show missed-call revenue vs subscription cost.",
  },
  {
    id: "033",
    title: "Cold Email at Scale",
    speaker: "Skool",
    source: "skool",
    date: "2026-01-22",
    hook: "1,000/day system. 3x reply rates targeting secondary cities.",
    summary: [
      "1,000 emails/day is the volume target",
      "Secondary cities = 3x reply rates vs metro areas",
      "Warm up domains, rotate senders, personalize at scale",
    ],
    details: [
      "Infrastructure: multiple domains, warm-up period, sender rotation",
      "Secondary cities have less inbox competition — roofers actually read email",
      "Personalization: city name + company name + specific pain point",
      "Follow-up sequence: 3 touches over 7 days, then move to next batch",
    ],
    links: [
      { label: "Vault Entry 033", href: "/command-center/vault/033" },
      { label: "Outreach Pipeline", href: "/command-center?tab=outreach" },
    ],
    tags: ["outreach", "email", "acquisition"],
    featured: true,
  },
  {
    id: "052",
    title: "Review Collection + AI Response",
    speaker: "Skool",
    source: "skool",
    date: "2026-02-15",
    hook: "After job → sentiment → SEO review → Google link. Automated.",
    summary: [
      "Automated review collection after every completed job",
      "AI sentiment check before asking for public review",
      "Direct Google review link = frictionless 5-star pipeline",
    ],
    details: [
      "Trigger: job marked complete → SMS to homeowner",
      "Sentiment gate: if negative, route to private feedback (don't publish)",
      "If positive: auto-generate SEO-friendly review draft, send Google review link",
      "AI responds to every Google review within 24hrs — signals active business to Google",
    ],
    links: [
      { label: "Vault Entry 052", href: "/command-center/vault/052" },
    ],
    tags: ["reviews", "seo", "automation", "retention"],
    featured: true,
    revenuePlay: "Automated review pipeline = SEO compound interest. More reviews → more visibility → more leads.",
  },
  {
    id: "019",
    title: "Clinic Management Pattern",
    speaker: "Gal",
    source: "skool",
    date: "2025-12-20",
    hook: "Walk in, observe pain, build action dashboard. That's Mission Control.",
    summary: [
      "Best products come from observing the workflow, not asking what they want",
      "Build the dashboard they'd build themselves if they could code",
      "Action-oriented: every screen should have a clear next action",
    ],
    details: [
      "Gal's approach: shadow the clinic, watch what they do, build the tool around their actual workflow",
      "Applied to RuufPro: Mission Control IS this — the roofer's daily cockpit",
      "Every panel should answer 'what do I do next?' not 'here's your data'",
      "Reduce decision fatigue: surface the one thing that matters most right now",
    ],
    links: [
      { label: "Vault Entry 019", href: "/command-center/vault/019" },
    ],
    tags: ["product", "ux", "philosophy"],
    featured: true,
  },
];

// ─── Helper functions ──────────────────────────────────────────

export function getFeaturedEntries(): VaultEntry[] {
  return VAULT_ENTRIES.filter((e) => e.featured);
}

export function getRecentEntries(count: number = 10): VaultEntry[] {
  return [...VAULT_ENTRIES]
    .sort((a, b) => b.date.localeCompare(a.date))
    .slice(0, count);
}

export function getEntriesByTag(tag: string): VaultEntry[] {
  return VAULT_ENTRIES.filter((e) => e.tags.includes(tag));
}

export function getEntriesBySource(source: string): VaultEntry[] {
  return VAULT_ENTRIES.filter((e) => e.source === source);
}

export function getVaultStats() {
  return {
    total: VAULT_ENTRIES.length,
    featured: VAULT_ENTRIES.filter((e) => e.featured).length,
    withRevenuePlays: VAULT_ENTRIES.filter((e) => e.revenuePlay).length,
    tags: Array.from(new Set(VAULT_ENTRIES.flatMap((e) => e.tags))),
    sources: Array.from(new Set(VAULT_ENTRIES.map((e) => e.source))),
  };
}
